// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Geography$ReactTemplate = require("./Geography.bs.js");
var Geographies$ReactTemplate = require("./Geographies.bs.js");
var ComposableMap$ReactTemplate = require("./ComposableMap.bs.js");
var ZoomableGroup$ReactTemplate = require("./ZoomableGroup.bs.js");

var component = ReasonReact.statelessComponent("MapComponent");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "Map"
                        }, ReasonReact.element(/* None */0, /* None */0, ComposableMap$ReactTemplate.make(/* array */[ReasonReact.element(/* None */0, /* None */0, ZoomableGroup$ReactTemplate.make(/* array */[ReasonReact.element(/* None */0, /* None */0, Geographies$ReactTemplate.make("world-50m.json", /* array */[(function (geographies, p) {
                                                          return Belt_List.map(geographies, (function (g) {
                                                                        return ReasonReact.element(/* Some */[""], /* None */0, Geography$ReactTemplate.make(g, p, /* array */[]));
                                                                      }));
                                                        })]))]))])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
